docusign:
    accountId: ENC[AES256_GCM,data:rRBKnW0Vk4yRalKln4zOrj7++J8xnNiRezxBQJOneEzVgEYd,iv:hytSbZV3U3kQ9w8tgfaXNdIqobpRtKdru+CtTtLXqJ8=,tag:IK3y4U2q8ddG3D53eXNcBw==,type:str]
    basePath: ENC[AES256_GCM,data:9mP091mv2Y5pBZ7FdaUJiT+ePiMt2sQ63CwDBY9P5slr1w==,iv:QK7frtTIKfbkIPwh5LD3/L/0uA2d2AL9Gy78g1k8Y68=,tag:CIHNRnPSCYkteKwnRk8jXA==,type:str]
    integrationKey: ENC[AES256_GCM,data:/yaOS8Gzn3YOAxiefKBr2b2rqxF5fB61qW8ovfsYL0xZxOpM,iv:Y7D3T2axr9TJbnF5d4Wjce/U4hsEuXv5WwUFJSFrEmc=,tag:XKea2EkrwNt8mh1FKSZvCg==,type:str]
    userId: ENC[AES256_GCM,data:vLnGyrqh1svd7oxauTsKVtbeoXE0OBqvqX/4vPL8UQ9m75sr,iv:9MNlUXN2tn/rMe2g7EIZ8Mb2X/ps+3W+h/IQVtkZC00=,tag:Hq8WLpQmXnAXynUaAh063w==,type:str]
spring:
    application:
        name: ENC[AES256_GCM,data:POzgLnGL8nw=,iv:uIR/pEbcqF9jR+uOlhWerS97Y90nzQYUaaYeXvclZ/g=,tag:MdcgwmoOfx/2ln00U724qQ==,type:str]
    data:
        mongodb:
            database: ENC[AES256_GCM,data:8Y4OJdIBg9HAUX6BzAV1,iv:3/YIZJB7JHxFn5HiDgULpld3MDcYVXIkkhkecxpO6FA=,tag:+JCa5rjyBzz4WV4KVxHnYQ==,type:str]
            uri: ENC[AES256_GCM,data:Jukb4D1wzv2mMg/B0TyliU1buoqcIeQ3xAHFZtCzZWOxChbpCwFiMZ/0WHH8QsgYFy4qYBCl9/Ad2Gvffc7ienYo6RWWiDU1fTr2rxWcB5J6VjIoX/w7,iv:ZVZptcgFIRz4E6dEMEw95OYXW5nwdVfASTuN7tcDjnk=,tag:o3Jlq/kLVcFMBJ/lIV6GUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-05-22T10:17:35Z"
    mac: ENC[AES256_GCM,data:nUd+wLWtD/3k2XCzvgEKqVywIgT8FnLoFLJPkf7NVUk7vXC8yziOoeHM+HGFEny6/lfrkrF1IuSCFLUT+gAcDJgP3icTgehm0Rb0nxZthuNfGZaniFTuB8xndIF9rw/AQn0hFNZspZD9P7s1Fg77QrYsBGhSNRWPE7T+yoQWAzc=,iv:h+2njESyAc4hjUELC3KPQv2MFG0IJbnLdZsgXcBoma4=,tag:HD2g7quBYweA6KkZdIKEmQ==,type:str]
    pgp:
        - created_at: "2024-05-22T10:17:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DeF21iO5u6jYSAQdAt81FZL5/fhSgI/9IFSM8q5HsNKSjVDbT/ON8r4uNgX4w
            1t9dADQBa8+jaHvVYicGCfJN5JsUDDF62Lr5W3p6rm4SCtNN5iYk94vuzvjfkfLE
            1GYBCQIQziSzTdWw3NkBbjfn+bk6JRmRTeivTb0SOBQtGLdmsJxfMDnH8aGxj9KJ
            Ic6gi0V6xjfpiJVC8D4fDzfOm5tQWxgttUP1lS3J5eUjzM5X64pXoKOLCqckuaEt
            MDn4KyKn8V8=
            =fcUZ
            -----END PGP MESSAGE-----
          fp: 3B0903815C34A9D54664029CE3938744BCBCC399
    unencrypted_suffix: _unencrypted
    version: 3.8.1
