name: Trigger auto deployment for spring-patients-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/spring-patients-app-AutoDeployTrigger-28f621c4-7489-4c8c-b6dc-130177d1f994.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SPRINGPATIENTSAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SPRINGPATIENTSAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SPRINGPATIENTSAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.SPRINGPATIENTSAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SPRINGPATIENTSAPP_REGISTRY_PASSWORD }}
          containerAppName: spring-patients-app
          resourceGroup: patients-app
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


